### ISSUE TITLE
doesn't work at all in node 14.17.0 on windows 10

### ISSUE THREAD

**Issue by JustifydWarrior** [ravangen/graphql-rate-limit#233]
```
Error: Cannot find module 'graphql-middleware'
Require stack:
- server\node_modules\graphql-shield\dist\shield.js
- server\node_modules\graphql-shield\dist\index.js
- server\node_modules\graphql-rate-limit\dist\index.js
- server\resolvers.js
- server\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (server\node_modules\graphql-shield\dist\shield.js:5:30)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'server\node_modules\graphql-shield\dist\shield.js',
    'server\node_modules\graphql-shield\dist\index.js',
    'server\node_modules\graphql-rate-limit\dist\index.js',
    'server\resolvers.js',
    'server\index.js'
  ]
}

**Comment by JustifydWarrior** [comment]
looks like graphql-shield is missing graphql-middleware as a dependency, i don't even see it as a peer in the package.json.

the fix looks like adding it as a peer dep inside graphql-rate-limit

**Comment by JustifydWarrior** [comment]
looks like graphql-shield has graphql-middleware as a peer dep in the graphql-shield/package.json but it's not being reported as a peer upon install.

the fix looks like adding graphql-middleware as a peer dep inside graphql-rate-limit

**Comment by ravangen** [comment]
👋 @JustifydWarrior

This library does not use `graphql-middleware`, so I am not sure why it should be a peer dependency. Similarly, it doesn't use `graphql-shield`. And it looks like `graphql-shield` does have a peer dependency for `graphql-middleware` ([source](https://github.com/maticzav/graphql-shield/blob/8fdb22f7165bb2517a591088cc4d828737445a3c/packages/graphql-shield/package.json#L34)).

**Comment by JustifydWarrior** [comment]
@ravangen so sorry, i reported this to the wrong repo.

i am using https://www.npmjs.com/package/graphql-rate-limit

which i guess is at https://github.com/teamplanes/graphql-rate-limit

and i think the fix is actually adding `graphql-shield` as peerDependency or dependancy.
