### ISSUE TITLE
about rate-limit headers in response

### ISSUE THREAD

**Issue by chenrui333** [ravangen/graphql-rate-limit#302]
👋  Thanks for creating this project, I wonder if there is any way that I can see the rate-limit related information in the http response. Thanks!

This is what I have got so far with some dummy setup
```
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 846
< ETag: W/"34e-zNqtLJPRwRT52bI2MkoWmsTpvA8"
< Date: Wed, 23 Mar 2022 19:31:27 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
{"errors":[{"message":"Too many requests, please try again in 13 seconds.","locations":[{"line":2,"column":5}],"path":["hello"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"message":"Too many requests, please try again in 13 seconds.","stacktrace":["GraphQLError: Too many requests, please try again in 13 seconds.","    at defaultOnLimit (/Users/rui/open-source/apollo-server-vercel/node_modules/graphql-rate-limit-directive/dist/index.js:70:11)","    at /Users/rui/open-source/apollo-server-vercel/node_modules/graphql-rate-limit-directive/dist/index.js:128:28","    at Generator.throw (<anonymous>)","    at rejected (/Users/rui/open-source/apollo-server-vercel/node_modules/graphql-rate-limit-directive/dist/index.js:6:65)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)"]}}}],"data":{"hello":null}}
```

**Comment by chenrui333** [comment]
based on my readings of #276, it looks like I have to update the apolloserver to consume the context information and generating the rate-limit related headers. Thanks!

**Comment by ravangen** [comment]
Yes, the library provides a way to capture limits experienced by each request. You will have to write some server code to fetch that data from context and place it in the HTTP headers and/or GraphQL extensions.
